//! One frame of the window: panels, dropped files, then the actions.

use eframe::egui::{self, Id, Panel, RichText, Ui};

use super::{Action, TbdSubtitlesApp, feature_views};
use crate::core::ui::MUTED_TEXT;

impl eframe::App for TbdSubtitlesApp {
    fn ui(&mut self, ui: &mut Ui, _frame: &mut eframe::Frame) {
        let actions = self.frame_ui(ui);
        self.apply(actions);
    }
}

impl TbdSubtitlesApp {
    /// Draw one frame and return the actions it asks for; changes nothing itself.
    pub(super) fn frame_ui(&self, ui: &mut Ui) -> Vec<Action> {
        let mut actions = Vec::new();
        let dropped = ui.ctx().input(|input| {
            input
                .raw
                .dropped_files
                .iter()
                .map(|file| file.path().to_path_buf())
                .collect::<Vec<_>>()
        });
        if !dropped.is_empty() {
            actions.push(Action::QueueVideos(dropped));
        }
        Panel::left(Id::new("queue"))
            .resizable(true)
            .default_size(320.0)
            .show(ui, |ui| feature_views::queue_ui(ui, self, &mut actions));
        egui::CentralPanel::default().show(ui, |ui| {
            ui.heading(super::APP_NAME);
            ui.label(
                RichText::new(
                    "Subtitles are generated by the pipeline stages, which are not built yet. \
                     Queued videos wait here.",
                )
                .color(MUTED_TEXT),
            );
        });
        actions
    }
}
